sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: local
    port: 3306
    database: sky_take_out
    username: sky_take_out
    password: root

  alioss:
    endpoint:
    access-key-id:
    access-key-secret:
    bucket-name:

  redis:
    host:
    port:
    database:
    password:

  wechat:
    appid:
    secret:

#    微信支付相关参数，未申请微信支付功能Api，故参数置空
    mchid :
    mchSerialNo:
    privateKeyFilePath:
    apiV3Key:
    weChatPayCertFilePath:
    notifyUrl:
    refundNotifyUrl:
#  百度地图 派送范围检测
  shop:
  baidu:

